/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.intsuperior.vista;

/**
 *
 * @author marcelopula
 */
public class programacionVisual extends javax.swing.JFrame {

    /**
     * Creates new form programacionVisual
     */
    public programacionVisual() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        btngrupopciones. add (rbtnfalso1);
        btngrupopciones. add (rbtnverdadero1);
        PREGUNTA2. add (FALSO2);
        PREGUNTA2. add (verP2);
        PREGUNTA3. add (F3);
        PREGUNTA3. add (V3);
        PREGUNTA4. add (F4);
        PREGUNTA4. add (V4);
        PREGUNTA5. add (F5);
        PREGUNTA5. add (V5);
        PREGUNTA6. add (F6);
        PREGUNTA6. add (V6);
        PREGUNTA7. add (F7);
        PREGUNTA7. add (V7);
        PREGUNTA8. add (F8);
        PREGUNTA8. add (V8);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrupopciones = new javax.swing.ButtonGroup();
        PREGUNTA2 = new javax.swing.ButtonGroup();
        PREGUNTA3 = new javax.swing.ButtonGroup();
        PREGUNTA4 = new javax.swing.ButtonGroup();
        PREGUNTA5 = new javax.swing.ButtonGroup();
        PREGUNTA6 = new javax.swing.ButtonGroup();
        PREGUNTA7 = new javax.swing.ButtonGroup();
        PREGUNTA8 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbtnverdadero1 = new javax.swing.JRadioButton();
        rbtnfalso1 = new javax.swing.JRadioButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        verP2 = new javax.swing.JRadioButton();
        FALSO2 = new javax.swing.JRadioButton();
        V3 = new javax.swing.JRadioButton();
        F3 = new javax.swing.JRadioButton();
        V4 = new javax.swing.JRadioButton();
        F4 = new javax.swing.JRadioButton();
        V5 = new javax.swing.JRadioButton();
        F5 = new javax.swing.JRadioButton();
        V6 = new javax.swing.JRadioButton();
        F6 = new javax.swing.JRadioButton();
        V7 = new javax.swing.JRadioButton();
        F7 = new javax.swing.JRadioButton();
        V8 = new javax.swing.JRadioButton();
        F8 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtobj = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EVALUACION PROGRAMACION VISUAL");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Fecha:");

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        jLabel3.setText("1.- ¿ Los métodos son funciones definidas dentro de una clase?");

        jLabel4.setText("A.RESPONDA VERDADERO O FALSO (C/P1pts)");

        rbtnverdadero1.setText("VERDADERO");

        rbtnfalso1.setText("FALSO");

        jScrollBar1.setBlockIncrement(50);

        jLabel5.setText("2.- Un obejeto JFrame es una ventana con barra de título y un borde,y de manera predeterminada se despliega en pantalla sin la necesidad de invocar a su método show.");

        jLabel6.setText("3.-¿ Los métodos pueden además tener otros argumentos explícitos que van entre paréntesis,a contiuación del nombre del método?");

        jLabel7.setText("4.-¿ El código comprendido entre las llaves {..} es el cuerpo o body del método?");

        jLabel8.setText("5.- Un constructor es un método que se llama automáticamente cada vez que se crea un objero de una clase.");

        jLabel9.setText("6.- La principal misión del constructor es reservar e inializar la variable miembro de la clase.");

        jLabel10.setText("7.- Los métodos constructores no tienen valor de retorno y su nombre no debe ser el mismo que el de clase.");

        jLabel11.setText("8.- El operador más (+) se utiliza también para concatenar cadenas de caracteres.");

        jLabel12.setText("COMPLETE");

        verP2.setText("VERDADERO");

        FALSO2.setText("FALSO");

        V3.setText("VERDADERO");

        F3.setText("FALSO");

        V4.setText("VERDADERO");

        F4.setText("FALSO");

        V5.setText("VERDADERO");

        F5.setText("FALSO");

        V6.setText("VERDADERO");

        F6.setText("FALSO");

        V7.setText("VERDADERO");

        F7.setText("FALSO");

        V8.setText("VERDADERO");

        F8.setText("FALSO");

        jLabel13.setText("public class Ejecutor{");

        jLabel14.setText("  public static void main (String[ ] args{");

        jLabel15.setText("//crear un objeto objeto de la clase coordinador");

        jLabel16.setText("Coordinador");

        txtobj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtobjActionPerformed(evt);
            }
        });

        jLabel17.setText("= new Coordinador();");

        jLabel18.setText("objeto.mensualScanner();");

        jLabel19.setText("Operaciones op");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1640, Short.MAX_VALUE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(verP2)
                                                .addGap(35, 35, 35)
                                                .addComponent(FALSO2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rbtnverdadero1)
                                                .addGap(33, 33, 33)
                                                .addComponent(rbtnfalso1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(V3)
                                                .addGap(34, 34, 34)
                                                .addComponent(F3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(V4)
                                                .addGap(26, 26, 26)
                                                .addComponent(F4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(V5)
                                                .addGap(28, 28, 28)
                                                .addComponent(F5))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(V6)
                                                .addGap(27, 27, 27)
                                                .addComponent(F6))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(V8)
                                                .addGap(18, 18, 18)
                                                .addComponent(F8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(V7)
                                                .addGap(27, 27, 27)
                                                .addComponent(F7))
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtobj, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(1269, 1269, 1269)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnverdadero1)
                            .addComponent(rbtnfalso1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(verP2)
                            .addComponent(FALSO2))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(V3)
                            .addComponent(F3))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(V4)
                            .addComponent(F4))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(F5)
                            .addComponent(V5))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(V6)
                            .addComponent(F6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F7)
                            .addComponent(V7))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F8)
                            .addComponent(V8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtobj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtobjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtobjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtobjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(programacionVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(programacionVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(programacionVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(programacionVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new programacionVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton F3;
    private javax.swing.JRadioButton F4;
    private javax.swing.JRadioButton F5;
    private javax.swing.JRadioButton F6;
    private javax.swing.JRadioButton F7;
    private javax.swing.JRadioButton F8;
    private javax.swing.JRadioButton FALSO2;
    private javax.swing.ButtonGroup PREGUNTA2;
    private javax.swing.ButtonGroup PREGUNTA3;
    private javax.swing.ButtonGroup PREGUNTA4;
    private javax.swing.ButtonGroup PREGUNTA5;
    private javax.swing.ButtonGroup PREGUNTA6;
    private javax.swing.ButtonGroup PREGUNTA7;
    private javax.swing.ButtonGroup PREGUNTA8;
    private javax.swing.JRadioButton V3;
    private javax.swing.JRadioButton V4;
    private javax.swing.JRadioButton V5;
    private javax.swing.JRadioButton V6;
    private javax.swing.JRadioButton V7;
    private javax.swing.JRadioButton V8;
    private javax.swing.ButtonGroup btngrupopciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rbtnfalso1;
    private javax.swing.JRadioButton rbtnverdadero1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtobj;
    private javax.swing.JRadioButton verP2;
    // End of variables declaration//GEN-END:variables
}
